import Link from 'next/link'
import { Activity, ArrowRight, Bot, Building2, CircleDollarSign, CreditCard, ShieldAlert } from 'lucide-react'

const metrics = [
  ['Active tenants', '248', '+12.4%', Building2, 'text-primary bg-primary/10'],
  ['Monthly recurring revenue', '$28,460', '+8.2%', CircleDollarSign, 'text-emerald-600 bg-emerald-500/10'],
  ['Tokens processed', '84.6M', '+21.8%', Activity, 'text-violet-600 bg-violet-500/10'],
  ['Widget uptime', '99.98%', 'Healthy', Bot, 'text-sky-600 bg-sky-500/10'],
] as const
const bars = [42, 54, 48, 69, 59, 83, 71, 92, 79, 88, 74, 96]

export default function AdminPage() {
  return <div className="space-y-7"><section className="flex flex-col gap-4 border-b border-border pb-6 sm:flex-row sm:items-end sm:justify-between"><div><p className="font-mono text-xs font-semibold uppercase tracking-[0.2em] text-primary">Platform intelligence</p><h1 className="mt-2 text-3xl font-semibold tracking-tight sm:text-4xl">Command center</h1><p className="mt-2 text-sm text-muted-foreground">Your platform’s health, growth, and urgent actions at a glance.</p></div><Link href="/admin/tenants/new" className="rounded-lg bg-primary px-3.5 py-2 text-center text-xs font-semibold text-primary-foreground">Create tenant</Link></section><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{metrics.map(([label, value, change, Icon, tint]) => <div key={label} className="rounded-2xl border border-border bg-card p-5 shadow-xs"><span className={`grid size-9 place-items-center rounded-xl ${tint}`}><Icon className="size-4" /></span><p className="mt-4 text-2xl font-bold tracking-tight">{value}</p><div className="mt-1 flex justify-between gap-2"><span className="text-xs text-muted-foreground">{label}</span><span className="text-[10px] font-semibold text-emerald-600">{change}</span></div></div>)}</section><section className="grid gap-5 xl:grid-cols-[1.6fr_1fr]"><div className="rounded-2xl border border-border bg-card p-5 shadow-xs sm:p-6"><div className="flex justify-between"><div><h2 className="text-base font-semibold">Usage trend</h2><p className="mt-1 text-xs text-muted-foreground">Token consumption, last 30 days</p></div><Link href="/admin/usage" className="text-xs font-semibold text-primary">View usage</Link></div><div className="mt-7 flex h-44 items-end gap-2 sm:gap-3">{bars.map((height, index) => <div className="flex h-full flex-1 items-end" key={index}><div className={`w-full rounded-t-md ${index === bars.length - 1 ? 'bg-primary' : 'bg-primary/20'}`} style={{ height: `${height}%` }} /></div>)}</div></div><div className="rounded-2xl border border-border bg-card p-5 shadow-xs sm:p-6"><div className="flex justify-between"><div><h2 className="text-base font-semibold">Needs attention</h2><p className="mt-1 text-xs text-muted-foreground">Issues requiring a decision</p></div><ShieldAlert className="size-5 text-amber-500" /></div><div className="mt-5 space-y-4"><Notice color="bg-amber-500" title="7 tenants nearing their limit" /><Notice color="bg-rose-500" title="2 failed payments need follow-up" /><Notice color="bg-sky-500" title="3 widget domains unverified" /></div></div></section><section className="grid gap-4 md:grid-cols-3"><Shortcut href="/admin/tenants" icon={Building2} title="Tenant directory" text="Manage access, plans, credits and workspace health." /><Shortcut href="/admin/payments" icon={CreditCard} title="Payment operations" text="Review invoices, failures and subscription changes." /><Shortcut href="/admin/widgets" icon={Bot} title="Widget fleet" text="Configure delivery and control embeds globally." /></section></div>
}
function Notice({ color, title }: { color: string; title: string }) { return <div className="flex items-center gap-3"><span className={`size-2 rounded-full ${color}`} /><span className="text-xs font-medium">{title}</span></div> }
function Shortcut({ href, icon: Icon, title, text }: { href: string; icon: typeof Building2; title: string; text: string }) { return <Link href={href} className="group rounded-2xl border border-border bg-card p-5 shadow-xs transition hover:border-primary/40"><Icon className="size-5 text-primary" /><h2 className="mt-4 text-sm font-semibold">{title}</h2><p className="mt-1 text-xs leading-relaxed text-muted-foreground">{text}</p><span className="mt-4 inline-flex items-center gap-1 text-xs font-semibold text-primary">Open <ArrowRight className="size-3.5 transition group-hover:translate-x-1" /></span></Link> }
