'use client'

import { useState } from 'react'
import {
  ArrowRight, BarChart3, Check, ChevronDown, Database,
  Clock3, FileText, Headphones, Menu, Play, ShieldCheck, Sparkles, X, Zap,
} from 'lucide-react'
import { Button } from '@/components/ui/button'

const features = [
  { icon: FileText, title: 'Bring your knowledge in', text: 'Upload PDFs, DOCX files, policies, FAQs, and product documentation into an isolated workspace.', badge: 'Documents' },
  { icon: Sparkles, title: 'Test grounded answers', text: 'Use Playground to evaluate retrieval, citations, history, and token usage before you deploy.', badge: 'Playground' },
  { icon: ShieldCheck, title: 'Deploy with control', text: 'Create restricted API keys, embed the widget, or call the chat API while keeping every tenant isolated.', badge: 'Integration' },
]

const faqs: [string, string][] = [
  ['What is VectorBase?', 'A multi-tenant RAG control plane for teams that want to build, configure, test, and embed customer-support chatbots grounded in their own knowledge.'],
  ['How does a workspace get ready?', 'Upload and process your documents, test representative questions in Playground, then create an API key and deploy through Integration.'],
  ['How are payments and token credits handled?', 'Billing uses Razorpay Checkout. Orders are verified server-side, webhooks reconcile payment state, and tokens are credited only after successful verification.'],
]

const steps = [
  ['01', 'Upload and index documents', 'Add PDFs, DOCX files, FAQs, policies, and product content, then wait for ingestion to finish before testing retrieval.'],
  ['02', 'Test in Playground', 'Ask representative questions, inspect citations, and refine retrieval and generation behavior against your workspace knowledge.'],
  ['03', 'Create a restricted API key', 'Allow only the website origins that should use the widget, and keep administrative credentials server-side.'],
  ['04', 'Embed and monitor', 'Deploy the widget or call the chat API, then review Conversations, API logs, and token usage as your workspace grows.'],
]

const pricingPlans = [
  { name: 'Starter', tokens: '10M', price: '₹249', description: 'For prototypes and small support teams.', featured: false },
  { name: 'Growth', tokens: '25M', price: '₹449', description: 'For growing customer-facing assistants.', featured: true },
  { name: 'Scale', tokens: '50M', price: '₹799', description: 'For high-volume knowledge workflows.', featured: false },
]

const tokenAddOn = { tokens: '1M', price: '₹29', description: 'Add extra capacity in repeatable 1M-token units.' }

function Logo() {
  return <a href="/" className="flex items-center gap-2.5"><span className="grid size-8 place-items-center rounded-xl bg-primary text-primary-foreground shadow-sm shadow-primary/30"><Database className="size-4" /></span><span className="font-mono text-sm font-bold tracking-tight">VectorBase</span></a>
}

function MarketingNav() {
  const [open, setOpen] = useState(false)
  const links = [['#support-agent', 'Support agent'], ['#setup', 'Setup'], ['#workflow', 'How it works'], ['#activity', 'Workspace activity'], ['#pricing', 'Pricing'], ['#faq', 'FAQ']]
  return <header className="sticky top-0 z-40 border-b border-border/60 bg-background/85 backdrop-blur-md">
    <div className="mx-auto flex h-16 max-w-7xl items-center justify-between px-5 sm:px-8"><Logo /><nav className="hidden items-center gap-7 text-sm text-muted-foreground md:flex">{links.map(([href, label]) => <a key={href} href={href} className="transition-colors hover:text-foreground">{label}</a>)}</nav><div className="hidden items-center gap-3 md:flex"><a href="/login" className="px-3 py-1.5 text-sm text-muted-foreground transition-colors hover:text-foreground">Sign in</a><Button asChild size="sm" className="rounded-lg shadow-sm shadow-primary/20"><a href="/register">Get started free</a></Button></div><button className="grid size-9 place-items-center rounded-lg border border-border md:hidden" onClick={() => setOpen(!open)} aria-label="Toggle menu">{open ? <X className="size-4" /> : <Menu className="size-4" />}</button></div>
    {open && <nav className="border-t border-border bg-card/95 px-5 py-5 backdrop-blur-sm md:hidden"><div className="flex flex-col gap-4 text-sm">{links.map(([href, label]) => <a key={href} href={href} onClick={() => setOpen(false)} className="text-muted-foreground hover:text-foreground">{label}</a>)}<hr className="border-border" /><a href="/login" className="text-muted-foreground hover:text-foreground">Sign in</a><Button asChild className="w-full rounded-lg"><a href="/register">Get started free</a></Button></div></nav>}
  </header>
}

function Hero() {
  return <section className="relative overflow-hidden border-b border-border"><div className="absolute inset-0 hero-wash" /><div className="absolute inset-0 dot-grid opacity-40" /><div className="pointer-events-none absolute -top-32 left-1/2 size-[700px] -translate-x-1/2 rounded-full bg-primary/10 blur-3xl" /><div className="relative mx-auto grid max-w-7xl gap-14 px-5 py-20 sm:px-8 sm:py-28 lg:grid-cols-[1.1fr_.9fr] lg:items-center">
    <div className="animate-fade-up"><div className="mb-6 inline-flex items-center gap-2 rounded-full border border-primary/30 bg-primary/10 px-3.5 py-1.5 font-mono text-[11px] font-medium text-primary"><span className="size-1.5 animate-pulse rounded-full bg-primary" />Knowledge-grounded AI support for your workspace</div><h1 className="max-w-3xl text-balance text-5xl font-bold leading-[1.05] tracking-[-0.04em] sm:text-6xl xl:text-7xl">Turn your product knowledge into <span className="gradient-text">trusted support.</span></h1><p className="mt-6 max-w-xl text-pretty text-base leading-7 text-muted-foreground sm:text-lg">VectorBase helps teams upload their knowledge, process it for retrieval, test grounded answers, and deploy a tenant-isolated chatbot through a widget or secure chat API.</p><div className="mt-9 flex w-full flex-col gap-3 sm:w-auto sm:flex-row"><Button asChild size="lg" className="w-full rounded-xl shadow-lg shadow-primary/25 sm:w-auto"><a href="/register">Start building free <ArrowRight className="ml-2 size-4" /></a></Button><Button asChild variant="outline" size="lg" className="w-full rounded-xl sm:w-auto"><a href="#platform"><Play className="mr-2 size-4" />See the platform</a></Button></div><div className="mt-8 flex flex-wrap items-center gap-x-6 gap-y-3 text-xs text-muted-foreground"><span className="flex items-center gap-2"><Check className="size-3.5 text-primary" />Tenant-isolated workspaces</span><span className="flex items-center gap-2"><Check className="size-3.5 text-primary" />Answers grounded in your documents</span><span className="flex items-center gap-2"><Check className="size-3.5 text-primary" />Restricted API keys</span></div></div>
        <div className="relative mx-auto w-full max-w-sm animate-fade-up lg:max-w-full" style={{ animationDelay: '0.1s' }}><div className="relative overflow-hidden rounded-3xl border border-primary/20 bg-card p-6 shadow-2xl glow-primary sm:p-8"><div className="absolute -right-16 -top-16 size-48 rounded-full bg-primary/10 blur-2xl" /><div className="relative"><div className="flex items-center justify-between"><div><p className="font-mono text-[10px] uppercase tracking-[0.2em] text-primary">Your online front desk</p><p className="mt-2 text-2xl font-semibold tracking-tight">Always open for questions.</p></div><span className="grid size-11 place-items-center rounded-2xl bg-primary text-primary-foreground shadow-lg shadow-primary/25"><Sparkles className="size-5" /></span></div><div className="mt-8 space-y-3"><div className="flex items-center gap-3 rounded-2xl border border-border bg-background p-3"><span className="grid size-9 place-items-center rounded-xl bg-emerald-500/12 text-emerald-700"><Check className="size-4" /></span><div><p className="text-sm font-medium">Answers from your business</p><p className="text-xs text-muted-foreground">Services, products, policies, and FAQs</p></div></div><div className="flex items-center gap-3 rounded-2xl border border-border bg-background p-3"><span className="grid size-9 place-items-center rounded-xl bg-sky-500/12 text-sky-700"><Zap className="size-4" /></span><div><p className="text-sm font-medium">Helpful around the clock</p><p className="text-xs text-muted-foreground">Let customers ask in their own words</p></div></div><div className="flex items-center gap-3 rounded-2xl border border-border bg-background p-3"><span className="grid size-9 place-items-center rounded-xl bg-amber-500/15 text-amber-700"><ShieldCheck className="size-4" /></span><div><p className="text-sm font-medium">You stay in control</p><p className="text-xs text-muted-foreground">Keep content current and answers grounded</p></div></div></div></div></div></div>
        <div className="pointer-events-none fixed bottom-28 right-12 z-50 translate-x-[0.8cm] translate-y-[0.8cm] sm:bottom-32 sm:right-20"><img src="/demoarrow.png" alt="" aria-hidden="true" className="h-28 w-28 object-contain sm:h-36 sm:w-36" /></div>
  </div></section>
}

function SupportDemos() {
  const demos = [
    { icon: ShieldCheck, title: "Doctor's website", q: 'Is Dr. Mehta experienced with sports injuries?', a: 'The clinic profile says Dr. Mehta focuses on sports medicine and has more than 12 years of clinical experience. For this demo, the clinic contact is +91 80 4567 8900, open Monday to Saturday from 9:00 AM to 6:00 PM. Call to confirm availability and book an appointment.', source: 'Doctor profile · experience, contact, and hours', accent: 'bg-emerald-500/12 text-emerald-700', answer: 'bg-emerald-500/10' },
    { icon: Database, title: 'Ecommerce store', q: 'Can I return shoes after trying them on?', a: 'The return policy allows unworn shoes to be returned within 30 days in the original packaging. Start the return from Orders, upload the order number if requested, and expect the refund after the warehouse inspection.', source: 'Return policy · eligibility, process, and refund', accent: 'bg-amber-500/15 text-amber-700', answer: 'bg-amber-500/10' },
    { icon: Sparkles, title: 'SaaS product', q: 'How do I invite a teammate to our workspace?', a: 'Open Profile, go to Workspace members, select Invite member, and enter their email address. You need the workspace role that can manage access; the invitee will receive a sign-in link.', source: 'Product docs · workspace administration', accent: 'bg-sky-500/15 text-sky-700', answer: 'bg-sky-500/10' },
    { icon: FileText, title: 'Education portal', q: 'When is the final assignment due?', a: 'Open the course calendar and select the current module to see the final assignment deadline and submission instructions. If the date is missing, contact the course coordinator before submitting late work.', source: 'Course guide · schedule and submission rules', accent: 'bg-violet-500/15 text-violet-700', answer: 'bg-violet-500/10' },
    { icon: Zap, title: 'Travel business', q: 'What is included in the weekend tour package?', a: 'The package includes accommodation, breakfast, and the guided activities listed in the itinerary. Transport and optional excursions are separate, so check the booking summary before payment.', source: 'Tour guide · package inclusions and booking', accent: 'bg-rose-500/15 text-rose-700', answer: 'bg-rose-500/10' },
    { icon: Database, title: 'Hotel website', q: 'What time is check-in, and does my room include breakfast?', a: 'Standard check-in is from 2:00 PM and check-out is by 11:00 AM. Breakfast is included only with eligible room plans; open your booking confirmation to verify your package. For arrival changes, contact the front desk using the number in your reservation.', source: 'Hotel guide · check-in, checkout, and room plans', accent: 'bg-cyan-500/15 text-cyan-700', answer: 'bg-cyan-500/10' },
  ]
  return <section id="support-agent" className="border-y border-border bg-muted/30"><div className="mx-auto max-w-7xl px-5 py-20 sm:px-8 sm:py-28"><div className="max-w-3xl"><p className="font-mono text-[11px] font-semibold uppercase tracking-widest text-primary">Helpful answers for your customers</p><h2 className="mt-4 text-3xl font-bold tracking-tight sm:text-5xl">Let your customers get <br className="hidden sm:block" />the right answer, right away.</h2><p className="mt-4 text-pretty leading-7 text-muted-foreground">Teach VectorBase about your business, services, policies, and products. Your customers can ask everyday questions and get clear answers based on the information you provide.</p></div><div className="mt-12 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{demos.map(({ icon: Icon, title, q, a, source, accent, answer }) => <article key={title} className="rounded-2xl border border-border bg-card p-5 shadow-sm card-hover"><div className="flex items-center gap-2.5 border-b border-border pb-4"><span className={`grid size-9 place-items-center rounded-xl ${accent}`}><Icon className="size-4" /></span><div><p className="text-sm font-semibold">{title}</p><p className="text-xs text-muted-foreground">Example conversation</p></div></div><div className="space-y-3.5 pt-5 text-sm"><div className="ml-6 rounded-2xl rounded-tl-sm bg-muted px-4 py-3 leading-5 text-foreground">{q}</div><div className={`rounded-2xl rounded-tl-sm px-4 py-3 leading-6 text-foreground ${answer}`}><span className="font-semibold text-foreground">Support agent</span><br />{a}<p className="mt-2.5 border-t border-black/10 pt-2.5 text-xs text-muted-foreground">{source}</p></div></div></article>)}</div><div className="mt-8 flex flex-wrap items-center gap-x-8 gap-y-3 text-xs text-muted-foreground">{['Answers from your indexed knowledge', 'Tenant-scoped retrieval', 'Widget or direct API deployment'].map((text) => <span key={text} className="flex items-center gap-2"><Check className="size-3.5 text-emerald-500" />{text}</span>)}</div></div></section>
}

function Platform() {
  return <section id="platform" className="mx-auto max-w-7xl px-5 py-20 sm:px-8 sm:py-28"><div className="max-w-2xl"><p className="font-mono text-[11px] font-semibold uppercase tracking-widest text-primary">What you get</p><h2 className="mt-4 text-3xl font-bold tracking-tight sm:text-5xl">Everything to ship helpful support.</h2><p className="mt-4 text-pretty leading-7 text-muted-foreground">One platform, from knowledge ingestion to a tested widget or direct chat API.</p></div><div className="mt-12 grid gap-px overflow-hidden rounded-2xl border border-border bg-border md:grid-cols-3">{features.map(({ icon: Icon, title, text, badge }) => <article key={title} className="group bg-card p-7 sm:p-8"><div className="flex items-start justify-between"><span className="grid size-11 place-items-center rounded-xl bg-primary/10 text-primary transition-colors duration-200 group-hover:bg-primary group-hover:text-primary-foreground"><Icon className="size-5" /></span><span className="rounded-full border border-border px-2.5 py-0.5 text-[10px] font-semibold uppercase tracking-widest text-muted-foreground">{badge}</span></div><h3 className="mt-7 text-lg font-semibold">{title}</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">{text}</p><a href="/register" className="mt-7 inline-flex items-center gap-1.5 text-xs font-semibold text-primary transition-all group-hover:gap-2">Explore feature <ArrowRight className="size-3.5" /></a></article>)}</div></section>
}

function Workflow() {
  return <section id="workflow" className="border-y border-border bg-card/40"><div className="mx-auto max-w-7xl px-5 py-20 sm:px-8 sm:py-28"><div className="grid gap-12 lg:grid-cols-[.75fr_1.25fr] lg:items-start"><div className="lg:sticky lg:top-28"><p className="font-mono text-[11px] font-semibold uppercase tracking-widest text-primary">How it works</p><h2 className="mt-4 text-3xl font-bold tracking-tight sm:text-5xl">From source document to support channel.</h2><p className="mt-4 leading-7 text-muted-foreground">A documented workflow for teams that care about grounded answers, tenant isolation, and safe deployment.</p><Button asChild className="mt-8 rounded-xl shadow-md shadow-primary/20"><a href="/register">Start building <ArrowRight className="ml-2 size-4" /></a></Button></div><div className="grid gap-4 sm:grid-cols-2">{steps.map(([number, title, text]) => <article key={number} className="group rounded-2xl border border-border bg-background p-6 card-hover"><p className="font-mono text-2xl font-bold gradient-text">{number}</p><h3 className="mt-6 text-base font-semibold">{title}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{text}</p></article>)}</div></div></div></section>
}

function Setup() {
  const setupSteps = [
    ['01', 'Create your workspace', 'Sign up and bring your support knowledge into one tenant-isolated Dashboard.'],
    ['02', 'Upload your documents', 'Add your FAQs, policies, product docs, or help-center content and let ingestion finish.'],
    ['03', 'Test and connect', 'Check answers in Playground, create an API key with Allowed Domains, and copy the Integration snippet.'],
  ]

  return <section id="setup" className="border-y border-border bg-primary/[0.035]"><div className="mx-auto max-w-7xl px-5 py-20 sm:px-8 sm:py-28"><div className="grid gap-10 lg:grid-cols-[.8fr_1.2fr] lg:items-start"><div><p className="font-mono text-[11px] font-semibold uppercase tracking-widest text-primary">Start in 2 minutes</p><h2 className="mt-4 text-3xl font-bold tracking-tight sm:text-5xl">Create a custom chatbot for your site.</h2><p className="mt-4 max-w-xl leading-7 text-muted-foreground">Set up your workspace, connect your knowledge, and publish a grounded support widget with a few focused steps.</p><Button asChild className="mt-8 rounded-xl shadow-md shadow-primary/20"><a href="/register">Create your chatbot <ArrowRight className="ml-2 size-4" /></a></Button></div><div className="space-y-4">{setupSteps.map(([number, title, text]) => <article key={number} className="flex gap-4 rounded-2xl border border-border bg-card p-5 shadow-sm"><span className="font-mono text-xl font-bold gradient-text">{number}</span><div><h3 className="font-semibold">{title}</h3><p className="mt-1 text-sm leading-6 text-muted-foreground">{text}</p></div></article>)}<div className="flex gap-4 rounded-2xl border border-primary/25 bg-primary/10 p-5"><span className="grid size-10 shrink-0 place-items-center rounded-xl bg-primary text-primary-foreground"><Headphones className="size-5" /></span><div><div className="flex items-center gap-2"><h3 className="font-semibold">Need a hand?</h3><Clock3 className="size-4 text-primary" /></div><p className="mt-1 text-sm leading-6 text-muted-foreground">A VectorBase representative can help integrate the chatbot on your behalf when you need support with the setup or deployment.</p></div></div></div></div></div></section>
}

function WorkspaceActivity() {
  const bars = [34, 42, 38, 55, 49, 63, 58, 72, 68, 79, 74, 88, 82, 94]
  return <section id="activity" className="mx-auto max-w-7xl px-5 py-20 sm:px-8 sm:py-28"><div className="grid gap-12 lg:grid-cols-2 lg:items-center"><div><p className="font-mono text-[11px] font-semibold uppercase tracking-widest text-primary">Workspace visibility</p><h2 className="mt-4 text-3xl font-bold tracking-tight sm:text-5xl">See what your knowledge base is doing.</h2><p className="mt-4 max-w-lg leading-7 text-muted-foreground">Review conversations, API activity, document status, and token usage from the authenticated Dashboard. Keep improving the knowledge your customers rely on.</p><ul className="mt-8 space-y-4 text-sm">{[[ShieldCheck, 'emerald', 'Tenant-safe by design.', 'Keep workspaces, keys, and data cleanly separated.'], [Zap, 'primary', 'Token usage stays visible.', 'Track capacity before a workspace runs out.'], [FileText, 'primary', 'Documents stay inspectable.', 'Review processing status and keep source content current.']].map(([Icon, color, strong, rest]) => <li key={strong as string} className="flex gap-3"><Icon className={`mt-0.5 size-4 shrink-0 text-${color}-500`} /><span><strong className="font-semibold">{strong as string}</strong><span className="ml-1 text-muted-foreground">{rest as string}</span></span></li>)}</ul></div><div className="rounded-2xl border border-border bg-card p-6 shadow-xl glow-primary"><div className="flex items-center justify-between"><div><p className="text-sm font-semibold">Dashboard activity</p><p className="mt-0.5 text-xs text-muted-foreground">Illustrative workspace view</p></div><BarChart3 className="size-5 text-primary" /></div><div className="mt-8 flex h-44 items-end gap-1.5">{bars.map((height, index) => <div key={index} className="flex-1 rounded-t-sm transition-all duration-500" style={{ height: `${height}%`, background: `oklch(${0.52 + (height / 100) * 0.15} 0.22 263 / ${0.5 + (height / 100) * 0.5})` }} />)}</div><div className="mt-5 grid grid-cols-3 gap-3 border-t border-border pt-5">{[['Docs', 'indexed'], ['Chats', 'reviewable'], ['Tokens', 'metered']].map(([value, label]) => <div key={label}><p className="font-mono text-xl font-bold gradient-text">{value}</p><p className="mt-0.5 text-[10px] text-muted-foreground">{label}</p></div>)}</div></div></div></section>
}

function FAQ() {
  const [active, setActive] = useState(0)
  return <section id="faq" className="border-t border-border bg-muted/30"><div className="mx-auto max-w-3xl px-5 py-20 sm:px-8 sm:py-28"><div className="text-center"><p className="font-mono text-[11px] font-semibold uppercase tracking-widest text-primary">Questions, answered</p><h2 className="mt-4 text-3xl font-bold tracking-tight sm:text-5xl">Start with confidence.</h2></div><div className="mt-12 divide-y divide-border overflow-hidden rounded-2xl border border-border bg-card">{faqs.map(([question, answer], index) => <div key={question}><button onClick={() => setActive(active === index ? -1 : index)} className="flex w-full items-center justify-between gap-4 px-6 py-5 text-left text-sm font-medium transition-colors hover:bg-muted/40"><span>{question}</span><ChevronDown className={`size-4 shrink-0 text-muted-foreground transition-transform duration-200 ${active === index ? 'rotate-180' : ''}`} /></button>{active === index && <p className="max-w-2xl px-6 pb-5 text-sm leading-6 text-muted-foreground animate-fade-up">{answer}</p>}</div>)}</div></div></section>
}

function CTA() {
  return <section className="relative overflow-hidden border-t border-border"><div className="absolute inset-0 hero-wash dot-grid opacity-50" /><div className="pointer-events-none absolute inset-0 flex items-center justify-center"><div className="size-[600px] rounded-full bg-primary/10 blur-3xl" /></div><div className="relative mx-auto max-w-4xl px-5 py-24 text-center sm:px-8 sm:py-32"><p className="font-mono text-[11px] font-semibold uppercase tracking-widest text-primary">Build on your knowledge</p><h2 className="mt-5 text-4xl font-bold tracking-tight sm:text-6xl">Turn your knowledge into a <span className="gradient-text">helpful support experience.</span></h2><p className="mx-auto mt-6 max-w-xl leading-7 text-muted-foreground">Build, test, and deploy a grounded assistant with a workspace designed for safe customer support.</p><div className="mt-10 flex flex-col items-center gap-3 sm:flex-row sm:justify-center"><Button asChild size="lg" className="w-full rounded-xl shadow-xl shadow-primary/25 sm:w-auto"><a href="/register">Start building free <ArrowRight className="ml-2 size-4" /></a></Button><Button asChild variant="outline" size="lg" className="w-full rounded-xl sm:w-auto"><a href="/login">Sign in to dashboard</a></Button></div></div></section>
}

function Pricing() {
  return <section id="pricing" className="border-t border-border"><div className="mx-auto max-w-7xl px-5 py-20 sm:px-8 sm:py-28"><div className="mx-auto max-w-2xl text-center"><p className="font-mono text-[11px] font-semibold uppercase tracking-widest text-primary">Simple token pricing</p><h2 className="mt-4 text-3xl font-bold tracking-tight sm:text-5xl">Choose room to grow.</h2><p className="mt-6 leading-7 text-muted-foreground">Start with the complete VectorBase platform, then add the token capacity your support workload needs.</p></div><div className="mt-12 grid gap-5 lg:grid-cols-3">{pricingPlans.map((plan) => <article key={plan.name} className={`relative flex flex-col rounded-2xl border bg-card p-6 shadow-sm ${plan.featured ? 'border-primary ring-1 ring-primary/20' : 'border-border'}`}>{plan.featured && <span className="absolute -top-3 left-5 rounded-full bg-primary px-3 py-1 text-[10px] font-semibold uppercase tracking-wider text-primary-foreground">Most popular</span>}<p className="text-sm font-semibold">{plan.name}</p><p className="mt-4 text-4xl font-bold tracking-tight">{plan.tokens}</p><p className="mt-1 text-xs text-muted-foreground">tokens per top-up</p><p className="mt-5 min-h-10 text-sm leading-5 text-muted-foreground">{plan.description}</p><div className="mt-6 border-t border-border pt-5"><span className="text-2xl font-semibold">{plan.price}</span><span className="ml-2 text-xs text-muted-foreground">one-time</span></div><a href="/register" className={`mt-7 inline-flex h-10 items-center justify-center rounded-xl px-4 text-sm font-medium transition-colors ${plan.featured ? 'bg-primary text-primary-foreground hover:bg-primary/90' : 'border border-border bg-background hover:bg-muted'}`}>Get started</a></article>)}</div><div className="mt-6 flex flex-col gap-4 rounded-2xl border border-dashed border-primary/40 bg-primary/5 p-5 sm:flex-row sm:items-center sm:justify-between sm:p-6"><div><p className="font-mono text-[10px] font-semibold uppercase tracking-widest text-primary">Flexible top-up</p><p className="mt-2 font-semibold">Need more capacity between plans?</p><p className="mt-1 text-sm text-muted-foreground">Buy additional tokens repeatedly in 1M-token units.</p></div><a href="/register" className="inline-flex h-10 items-center justify-center rounded-xl border border-primary/30 bg-background px-4 text-sm font-medium text-primary transition-colors hover:bg-primary/10 sm:shrink-0">Add {tokenAddOn.tokens} for {tokenAddOn.price}</a></div><p className="mt-6 text-center text-xs text-muted-foreground">Need a custom volume? Contact us for a tailored plan.</p></div></section>
}

function Footer() {
  return <footer className="border-t border-border bg-card/60"><div className="mx-auto flex max-w-7xl flex-col gap-6 px-5 py-8 text-xs text-muted-foreground sm:flex-row sm:items-center sm:justify-between sm:px-8"><Logo /><div className="flex flex-wrap gap-5"><a href="/dashboard" className="transition-colors hover:text-foreground">Dashboard</a><a href="/widget" className="transition-colors hover:text-foreground">Demo widget</a><a href="mailto:hello@vectorbase.dev" className="transition-colors hover:text-foreground">Contact</a></div><p>© 2026 VectorBase</p></div></footer>
}

export default function Page() {
  return <><MarketingNav /><main><Hero /><SupportDemos /><Platform /><Workflow /><Setup /><WorkspaceActivity /><Pricing /><FAQ /><CTA /></main><Footer /></>
}
