'use client'

import { FormEvent, useState } from 'react'
import Link from 'next/link'
import { Check, Clipboard, Loader2, ShieldCheck } from 'lucide-react'
import { ApiError, api } from '@/lib/api'

type CreatedTenant = { id: number; name: string; access_token: string; available_tokens: number }

export default function NewTenantPage() {
  const [form, setForm] = useState({ full_name: '', email: '', company_name: '', phone: '', password: '' })
  const [loading, setLoading] = useState(false), [error, setError] = useState(''), [created, setCreated] = useState<CreatedTenant | null>(null), [copied, setCopied] = useState(false)
  const set = (key: keyof typeof form, value: string) => setForm(current => ({ ...current, [key]: value }))
  const submit = async (event: FormEvent) => { event.preventDefault(); setLoading(true); setError(''); try { setCreated(await api.adminPost<CreatedTenant>('/api/v1/admin/tenants', { ...form, phone: form.phone || null })) } catch (e) { setError(e instanceof ApiError ? e.message : 'Could not create tenant.') } finally { setLoading(false) } }
  const copy = async () => { if (created?.access_token) { await navigator.clipboard.writeText(created.access_token); setCopied(true); setTimeout(() => setCopied(false), 1800) } }
  return <div className="mx-auto max-w-2xl py-4"><Link href="/admin" className="text-xs font-semibold text-primary hover:underline">← Back to command center</Link><div className="mt-7"><p className="font-mono text-xs uppercase tracking-[0.2em] text-primary">Tenant provisioning</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">Create a tenant</h1><p className="mt-2 text-sm text-muted-foreground">Set up a new organization, workspace owner, and initial access credentials.</p></div><form onSubmit={submit} className="mt-7 rounded-2xl border border-border bg-card p-5 shadow-xs sm:p-7"><div className="grid gap-4 sm:grid-cols-2"><Field label="Owner full name" value={form.full_name} onChange={v => set('full_name', v)} placeholder="Jamie Lee" required /><Field label="Work email" type="email" value={form.email} onChange={v => set('email', v)} placeholder="jamie@company.com" required /><Field label="Organization" value={form.company_name} onChange={v => set('company_name', v)} placeholder="Acme Inc." required /><Field label="Phone (optional)" value={form.phone} onChange={v => set('phone', v)} placeholder="+1 555 0100" /><Field label="Temporary password" type="password" value={form.password} onChange={v => set('password', v)} placeholder="At least 8 characters" required /></div>{error && <p role="alert" className="mt-4 text-sm text-destructive">{error}</p>}<button disabled={loading} className="mt-6 inline-flex h-10 items-center gap-2 rounded-lg bg-primary px-4 text-xs font-semibold text-primary-foreground disabled:opacity-60">{loading && <Loader2 className="size-4 animate-spin" />}Create tenant</button></form>{created && <section className="mt-5 rounded-2xl border border-emerald-500/30 bg-emerald-500/10 p-5"><div className="flex gap-3"><ShieldCheck className="mt-0.5 size-5 text-emerald-600" /><div><h2 className="font-semibold">Tenant created</h2><p className="mt-1 text-xs text-muted-foreground">Copy the initial access token now; the service should return it only once.</p></div></div><div className="mt-4 flex items-center gap-2 rounded-lg border border-border bg-card p-3"><code className="min-w-0 flex-1 break-all text-xs">{created.access_token}</code><button type="button" onClick={copy} className="rounded-md p-2 hover:bg-muted" aria-label="Copy token">{copied ? <Check className="size-4 text-emerald-600" /> : <Clipboard className="size-4" />}</button></div><p className="mt-3 text-xs text-muted-foreground">Tenant #{created.id} · {created.name} · {created.available_tokens.toLocaleString()} initial credits</p></section>}</div>
}
function Field({ label, value, onChange, placeholder, type = 'text', required }: { label: string; value: string; onChange: (value: string) => void; placeholder: string; type?: string; required?: boolean }) { return <label className="block text-xs font-medium">{label}<input type={type} required={required} value={value} onChange={e => onChange(e.target.value)} placeholder={placeholder} className="mt-1.5 h-10 w-full rounded-lg border border-input bg-background px-3 text-sm outline-none transition focus:ring-2 focus:ring-ring" /></label> }
