'use client'

import { useMemo, useState } from 'react'
import Link from 'next/link'
import { MoreHorizontal, Search, SlidersHorizontal } from 'lucide-react'
import { Status, tenants } from '@/components/admin-data'

export default function TenantsPage() {
  const [query, setQuery] = useState('')
  const rows = useMemo(() => tenants.filter(t => `${t.name} ${t.email} ${t.plan}`.toLowerCase().includes(query.toLowerCase())), [query])
  return <div className="space-y-6"><header className="flex flex-col gap-4 border-b border-border pb-6 sm:flex-row sm:items-end sm:justify-between"><div><p className="font-mono text-xs uppercase tracking-[0.2em] text-primary">Customer operations</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">Tenants</h1><p className="mt-2 text-sm text-muted-foreground">Manage workspaces, subscriptions, access, and customer credits.</p></div><Link href="/admin/tenants/new" className="rounded-lg bg-primary px-3.5 py-2 text-center text-xs font-semibold text-primary-foreground">New tenant</Link></header><section className="rounded-2xl border border-border bg-card shadow-xs"><div className="flex flex-col gap-3 border-b border-border p-5 sm:flex-row sm:justify-between"><p className="text-sm font-semibold">All workspaces <span className="ml-1 text-xs font-normal text-muted-foreground">248 total</span></p><div className="flex gap-2"><label className="flex h-9 items-center gap-2 rounded-lg border border-input bg-background px-3 sm:w-64"><Search className="size-3.5 text-muted-foreground"/><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search name or email" className="w-full bg-transparent text-xs outline-none"/></label><button className="grid size-9 place-items-center rounded-lg border border-border"><SlidersHorizontal className="size-3.5"/></button></div></div><div className="overflow-x-auto"><table className="w-full min-w-[820px] text-left"><thead className="bg-muted/30 text-[10px] uppercase tracking-wider text-muted-foreground"><tr><th className="px-5 py-3">Tenant</th><th>Plan / state</th><th>Token usage</th><th>Spend</th><th>Widget</th><th>Updated</th><th/></tr></thead><tbody>{rows.map(t => <tr key={t.id} className="border-t border-border hover:bg-muted/40"><td className="px-5 py-4"><Link href={`/admin/tenants/${t.id}`} className="font-medium text-sm hover:text-primary">{t.name}<span className="mt-0.5 block text-[11px] font-normal text-muted-foreground">{t.email}</span></Link></td><td><span className="mr-2 text-xs">{t.plan}</span><Status status={t.status}/></td><td><div className="w-28"><div className="mb-1 flex justify-between text-[10px] text-muted-foreground"><span>{t.usage}%</span><span>{t.chats}</span></div><div className="h-1.5 rounded-full bg-muted"><div className={`${t.usage > 80 ? 'bg-amber-500' : 'bg-primary'} h-full rounded-full`} style={{width: `${t.usage}%`}}/></div></div></td><td className="text-sm font-medium">{t.spend}</td><td className="text-xs">{t.widget ? '● Live' : 'Draft'}</td><td className="text-xs text-muted-foreground">{t.updated}</td><td className="pr-5"><Link href={`/admin/tenants/${t.id}`} aria-label={`Open ${t.name}`} className="inline-grid size-8 place-items-center rounded-md hover:bg-muted"><MoreHorizontal className="size-4"/></Link></td></tr>)}</tbody></table></div></section></div>
}
